# langues.py

LANGUES_PAR_PAYS = {
    "france": ["français", "anglais", "allemand", "espagnol", "arabe"],
    "allemagne": ["allemand", "anglais", "turc", "français"],
    "italie": ["italien", "anglais", "français"],
    "espagne": ["espagnol", "catalan", "anglais", "français", "galicien", "basque"],
    "portugal": ["portugais", "anglais", "espagnol"],
    "royaume-uni": ["anglais", "français", "gallois", "écossais"],
    "irlande": ["anglais", "irlandais"],
    "pays-bas": ["néerlandais", "anglais"],
    "belgique": ["français", "néerlandais", "allemand"],
    "suisse": ["allemand", "français", "italien", "romanche"],
    "autriche": ["allemand", "anglais"],
    "pologne": ["polonais", "anglais", "allemand"],
    "hongrie": ["hongrois", "anglais"],
    "suède": ["suédois", "anglais"],
    "norvège": ["norvégien", "anglais"],
    "finlande": ["finnois", "suédois", "anglais"],
    "danemark": ["danois", "anglais"],
    "grèce": ["grec", "anglais"],
    "turquie": ["turc", "kurde", "anglais"],
    "russie": ["russe", "anglais", "tatar", "ukrainien"],
    "ukraine": ["ukrainien", "russe", "anglais"],
    "états-unis": ["anglais", "espagnol"],
    "canada": ["anglais", "français"],
    "mexique": ["espagnol", "anglais"],
    "brésil": ["portugais", "espagnol", "anglais"],
    "argentine": ["espagnol", "anglais"],
    "colombie": ["espagnol", "anglais"],
    "chine": ["chinois", "anglais", "cantonais", "ouïghour"],
    "japon": ["japonais", "anglais"],
    "corée du sud": ["coréen", "anglais"],
    "inde": ["hindi", "anglais", "bengali", "tamoul", "télougou", "marathi"],
    "pakistan": ["ourdou", "anglais", "pendjabi"],
    "iran": ["persan", "anglais", "azéri", "kurde"],
    "israël": ["hébreu", "arabe", "anglais", "russe"],
    "arabie saoudite": ["arabe", "anglais"],
    "maroc": ["arabe", "berbère", "français", "espagnol"],
    "algérie": ["arabe", "berbère", "français"],
    "tunisie": ["arabe", "français"],
    "egypte": ["arabe", "anglais", "français"],
    "afrique du sud": ["anglais", "afrikaans", "zoulou", "xhosa"],
    "nigeria": ["anglais", "haoussa", "yoruba", "igbo"],
    "australie": ["anglais"],
    "nouvelle-zélande": ["anglais", "maori"],
    "indonésie": ["indonésien", "javanais", "anglais"],
    "malaisie": ["malais", "anglais", "tamoul", "mandarin"],
    "thailande": ["thaï", "anglais"],
    "viet nam": ["vietnamien", "anglais", "français"],
    "singapour": ["anglais", "mandarin", "malais", "tamoul"],
    "kazakhstan": ["kazakh", "russe", "anglais"],
    "ukraine": ["ukrainien", "russe"],
    "gréce": ["grec", "anglais"],
    "syrie": ["arabe", "kurde", "arménien"],
    "irak": ["arabe", "kurde", "anglais"],
    "afghanistan": ["dari", "pachto", "anglais"],
    "chine": ["mandarin", "cantonais", "ouïghour", "anglais"],
    "mongolie": ["mongol", "russe"],
    "cuba": ["espagnol"],
    "vénézuela": ["espagnol"],
    "chili": ["espagnol"],
    "pérou": ["espagnol", "quechua", "aymara"],
    "maroc": ["arabe", "berbère", "français"],
    "sénégal": ["français", "wolof"],
    "côte d'ivoire": ["français"],
    "mali": ["français", "bambara"],
    "rd congo": ["français", "lingala", "swahili"],
    "kenya": ["anglais", "swahili"],
    "éthiopie": ["amharique", "oromo", "anglais"],
    "egypte": ["arabe", "anglais"],
    "islande": ["islandais", "anglais"],
    "finlande": ["finnois", "suédois"],
    "lettonie": ["letton", "russe"],
    "lituanie": ["lituanien", "russe"],
    "estonie": ["estonien", "russe"],
    "slovaquie": ["slovaque", "hongrois"],
    "bulgarie": ["bulgare", "anglais"],
    "roumanie": ["roumain", "hongrois"],
    "croatie": ["croate"],
    "serbie": ["serbe"],
    "bosnie": ["bosnien", "croate", "serbe"],
    "albanie": ["albanais"],
    "monténégro": ["monténégrin"],
    "géorgie": ["géorgien", "russe"],
    "arménie": ["arménien", "russe"],
    "azerbaïdjan": ["azéri", "russe"],
    "turkménistan": ["turkmène", "russe"],
    "ouzbékistan": ["ouzbek", "russe"],
    "kirghizistan": ["kirghiz", "russe"],
    # ... à compléter si besoin avec d'autres pays
}
